apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: myapp
    team: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      type: gateway
  template:
    metadata:
      labels:
        app: myapp
        type: gateway
    spec:
      containers:
      - name: gateway
        image: boodiebo/my-gateway
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: myapp
    team: backend
spec:
  selector:
    app: myapp
    type: gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30081
  type: NodePort